import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/component/Header'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () =>{
  let data = await fetch("http://localhost:3000/api/callData")
  data = await data.json()
  return {
    props:{
      data
    }
  }
}

export default function Home({data}) {
  const [name,setName] = useState("")
  const [contact,setContact] = useState("")
  const [record, setRecord] = useState(data.data)
  

  const handleClick = async(e) =>{
    e.preventDefault();
    await fetch("http://localhost:3000/api/insertData",{
      method:"POST",
      body:JSON.stringify({name,contact}),
      headers:{
       "content-type":"application/json"
      }
    }).then(resp => resp.json()).then(resp=>setRecord([...record,resp.data]))
    setName("")
    setContact("")
  }

  
  return (
    <>
      <Head>
        <title>Phonebook/home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='w-full flex gap-4'>
        <div className='w-4/12 mt-5 px-5'>
              <form className='flex flex-col'>
                <h1>Insert Here:</h1>
                  <div className='flex flex-col'>
                  <label>Name</label>
                  <input type='text' className='px-2 py-1 border rounded'value={name} onChange={(e)=>setName(e.target.value)} />
                  </div>
                  <div className='flex flex-col'>
                  <label>Contact</label>
                  <input type='text' className='px-2 py-1 border rounded'value={contact} onChange={(e)=>setContact(e.target.value)} />
                  </div>
                  <button type='submit' className='px-2 py-1 bg-indigo-600 text-white rounded border mt-2' onClick={handleClick}>Submit</button>
              </form>
        </div>
        <div className='w-8/12'>
        <div className='flex'>
            <table className='border w-full'>
              <thead>
                <tr>
                  <th className='border'>Id</th>
                  <th className='border'>Name</th>
                  <th className='border'>Contact</th>
                  <th className='border'>Action</th>
                </tr>
              </thead>
              <tbody>
                {record.map((value,index) => (
                    <tr>
                  <td className='border'>{value._id}</td>
                  <td className='border'>{value.name}</td>
                  <td className='border'>{value.contact}</td>
                  <td className='border flex gap-2'>
                    <a href='' className='px-2 py-1 bg-red-600 text-white rounded'>Delete</a>
                    <a href='' className='px-2 py-1 bg-green-600 text-white rounded'>Edit</a>
                  </td>
                </tr>
                ))
                }
              </tbody>

            </table>

          </div>
        </div>

      </div>
     
    </>
  )
}
